### ISSUE TITLE
Low test accuracy

### ISSUE THREAD

**Issue by 1600012423** [uranusx86/BinaryNet-on-tensorflow#1]
The test accuracy is too low, only 46.68%.  I don't think this model works.

**Comment by uranusx86** [comment]
which data set do you use? MNIST or CIFAR10? or other data set?

**Comment by 1600012423** [comment]
MNIST, after training I tested it with the test data set. The training accuracy is 96%, but test accuracy is 48%.

**Comment by uranusx86** [comment]
I run my code again, and it seems everything work.
In first two step (i don't run the code completely), test accuracy can reach 95%.
Do you use my origin code when testing data set?
If you use your own code, please make sure do the right [image & label preprocessing](https://github.com/uranusx86/BinaryNet-on-tensorflow/blob/master/mnist.py#L68)

**Comment by uranusx86** [comment]
If you have no problem, I'll close this issue.
don't hesitate to reopen this issue if you still have some problems.
