### ISSUE TITLE
How to save binary or quantized weights? 

### ISSUE THREAD

**Issue by yaching1995** [uranusx86/BinaryNet-on-tensorflow#2]
When I useBinaryNet, the weights saved reflect the actual weights, not the quantized one. What should I do if I want to save binary or quantized weights? Thanks a lot.

**Comment by yaching1995** [comment]
> 
> 
> When I useBinaryNet, the weights saved reflect the actual weights, not the quantized one. What should I do if I want to save binary or quantized weights? Thanks a lot.

**Comment by uranusx86** [comment]
In my project, i don't save the binary weights directly.
I save the real weights instead for retraining network convenient.

If you want to get the binary weights, you have to get the real weights first, and do binarization.


Detail as follow:

1. get the tensor name in the checkpoint file.
```
from tensorflow.python.tools.inspect_checkpoint import print_tensors_in_checkpoint_file
import os
checkpoint_path = os.path.join("./", "model.ckpt")
print_tensors_in_checkpoint_file(file_name=checkpoint_path, tensor_name='', all_tensors=False)
```
you will see the name like "conv2d__binary_layer/kernel", "dense__binary_layer/kernel", only focus on the name ends with kernel or bias, and copy it.

2. then restore the checkpoint file into graph, and run the copied tensor name (remember add ":0" in the end, for example, if you want to get "conv2d__binary_layer/kernel", then type "conv2d__binary_layer/kernel:0"), you will get the real weight in the tensor.
```
import tensorflow as tf
restore_graph = tf.Graph()
with restore_graph.as_default():
    saver = tf.train.import_meta_graph("model.ckpt.meta", clear_devices=True)
restore_graph_def = restore_graph.as_graph_def()
sess =  tf.Session(graph=restore_graph)
saver.restore(sess, "./model.ckpt")
print(sess.run("conv2d__binary_layer/kernel:0"))
```

3. The last step, do binarization to get the binary weight. 
```
def binarization(W, H):
    Wb = H * (2. * np.round( np.clip( (W/H + 1.)/2., 0, 1) ) - 1.)
    return Wb

print(binarization( sess.run("conv2d__binary_layer/kernel:0"), 1.0))
```

Now, you can get the binary weight !!

**Comment by yaching1995** [comment]
@uranusx86 Thanks a lot!!
